version: "3.9"

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /srv/pterodactyl/database:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

  cache:
    image: redis:alpine
    restart: always

  panel:
    image: ghcr.io/pyrodactyl-oss/pyrodactyl:latest
    restart: always
    depends_on:
      - database
      - cache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/pterodactyl/var:/app/var
      - /srv/pterodactyl/nginx:/etc/nginx/http.d
      - /srv/pterodactyl/certs:/etc/letsencrypt
      - /srv/pterodactyl/logs:/app/storage/logs
    environment:
      # App
      APP_URL: ${APP_URL}
      APP_TIMEZONE: ${APP_TIMEZONE}
      APP_SERVICE_AUTHOR: ${APP_SERVICE_AUTHOR}
      APP_ENV: ${APP_ENV}
      APP_ENVIRONMENT_ONLY: ${APP_ENVIRONMENT_ONLY}

      # Database
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # Redis
      CACHE_DRIVER: ${CACHE_DRIVER}
      SESSION_DRIVER: ${SESSION_DRIVER}
      QUEUE_DRIVER: ${QUEUE_DRIVER}
      REDIS_HOST: ${REDIS_HOST}

      # Mail
      MAIL_FROM: ${MAIL_FROM}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}

      # Misc
      HASHIDS_LENGTH: ${HASHIDS_LENGTH}

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
