services:
  elytra:
    image: ghcr.io/pyrohost/elytra:latest
    restart: unless-stopped
    tty: true
    ports:
      - "8888:8080"
      - "2222:2022"
    environment:
      # Required: Panel connection and token
      ELYTRA_PANEL_LOCATION: "https://ptero.jsemolik.dev"
      ELYTRA_TOKEN_ID: "blablabla"
      ELYTRA_TOKEN: "blablabla"

      # Optional overrides / useful defaults
      TZ: "UTC"
      ELYTRA_DEBUG: "true"
      ELYTRA_API_HOST: "0.0.0.0"
      ELYTRA_API_PORT: "8080"
      ELYTRA_UID: "988"
      ELYTRA_GID: "988"

      # System path overrides (inside container)
      ELYTRA_SYSTEM_ROOT_DIRECTORY: "/var/lib/elytra"
      ELYTRA_SYSTEM_DATA: "/var/lib/elytra/volumes"
      ELYTRA_SYSTEM_LOG_DIRECTORY: "/var/log/elytra"

      # Docker integration (required for managing containers)
      ELYTRA_DOCKER_TMPFS_SIZE: "100"
      ELYTRA_SYSTEM_BACKUPS_RUSTIC_LOCAL_ENABLED: "false"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/:rw"
      - "/var/lib/elytra:/var/lib/elytra"
      - "/var/log/elytra:/var/log/elytra"
      - "/var/lib/elytra/config.yml:/etc/elytra/config.yml"
      - "/tmp/elytra:/tmp/elytra"


networks:
  default:
    driver: bridge
